### PR TITLE
feat: client and channel generation

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR adds the initial business logic converted from the old nunjucks code - https://github.com/jonaslagoni/dotnet-nats-template/tree/initial_version

### CODE REVIEW

**Comment by jonaslagoni** [comment]
If you want I can generate and include examples project, so you can inspect the out right here in the browser (press `.` right here in the PR). 

It might ease the review process?

**Review by derberg — COMMENTED** [review]
I think examples should be in the repo like in ts-nats template right?

also, maybe we should ping NATS folks, if they want to have a look now or later after merge they can jump into follow up improvements?

**Comment by jonaslagoni** [comment]
> I think examples should be in the repo like in ts-nats template right?

Examples are automatically included in the release process, which is why I dont normally include it in PR's as they just clutter things. However, I can make an exception here if it makes sense? 🤔 

> also, maybe we should ping NATS folks, if they want to have a look now or later after merge they can jump into follow up improvements?

Planning on pinging them once the template is "stable" and useable. Still need a couple of things for that. As including everything in one PR is impossible 😅

**Review by derberg — COMMENTED** [review]
from my point of view you can merge, I do not care much about generated code quality as my dotnet knowledge = 0 even though I wrote my bachelor degree in C# but it was about 15y ago 😆 

most important are good instruction on how someone can try it out manually to check it out, for not integration tests do not check how it works, they just check if project is building. I'd like to know how someone can go further here. Now we merge and release, but nobody will know how to use it, the to docs is also broken

**Comment by jonaslagoni** [comment]
Docs and un/marshalling models is next on the agenda 👍

**Comment by derberg** [comment]
@jonaslagoni can you at least fix readme broken link ?

**Comment by jonaslagoni** [comment]
> @jonaslagoni can you at least fix readme broken link ?

@derberg done 👍

**Comment by jonaslagoni** [comment]
@derberg 🙇

**Pull request merged**
