### PR TITLE
docs: removed all contributors to re-add it

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
As I manually added the initial docs for all contributors in the last PR, some formatting was incorrect. So this PR removes all references to start over.

### CODE REVIEW

**Comment by derberg** [comment]
@jonaslagoni why don't you use https://allcontributors.org/docs/en/cli/overview ? I always use it for initial setup, or when I need to add multiple people and do not want to do it one by one with bot. You do not even have to install it but use npx

**Comment by jonaslagoni** [comment]
> @jonaslagoni why don't you use https://allcontributors.org/docs/en/cli/overview ? I always use it for initial setup, or when I need to add multiple people and do not want to do it one by one with bot. You do not even have to install it but use npx

Not the biggest fan, it does not work that well either IMO.. But, I can give it some time and see how whether its worth it.

**Comment by jonaslagoni** [comment]
@derberg changed.

**Review by derberg — APPROVED** [review]
lgtm

**Pull request merged**
